### ISSUE TITLE
Netcheat Force Close?

### ISSUE THREAD

**Issue by Aurangzeb56** [Dnawrkshp/NetCheatPS3#4]
Hey Dnawrkshp, I wanted to ask you that every time I open NetcheatPS3 4.53 it closes back automatically. It stays there for around 2 to 3 seconds and then closes. Is there any problem with the exe file? I tried doing everything even troubleshooted the exe file but nothing seems to work. Could you please help me?

EDIT 1: I Uninstalled Lonely Screen, ApowerMirror and APowermanager, it seems to work fine after that. It doesn't close anymore. Might be some conflicting dll or something with those programs. Anyway Thanks. :D

**Comment by Dnawrkshp** [comment]
There's an issue with the auto-updater. I think it's because the site I've been using has implemented a new anti-DDOS service that is likely not allowing NetCheat connections through and then causing NC to throw an exception and crash.
I've heard that enabling airplane mode when launching NetCheat and then disabling it will fix the problem. I'll try and push a fix at some point.

**Comment by Dnawrkshp** [comment]
Also reopening because this is affecting many users and is not fixed.

**Comment by Aurangzeb56** [comment]
> There's an issue with the auto-updater. I think it's because the site I've been using has implemented a new anti-DDOS service that is likely not allowing NetCheat connections through and then causing NC to throw an exception and crash.
> I've heard that enabling airplane mode when launching NetCheat and then disabling it will fix the problem. I'll try and push a fix at some point.

Oh, well guess I just got lucky. I'll be looking forward to your fix. :)

**Comment by Dnawrkshp** [comment]
It's working for me now. I got the web admin to change some server settings which seem to have fixed it. If you have problems again please reopen this issue.

**Comment by Aurangzeb56** [comment]
> It's working for me now. I got the web admin to change some server settings which seem to have fixed it. If you have problems again please reopen this issue.

Works great for me again. Thanks. :)
