### ISSUE TITLE
Unhandled Exception: System.PlatformNotSupportedException: Speech Recognition is not available 

### ISSUE THREAD

**Issue by Klairm** [Dnawrkshp/NetCheatPS3#5]
Hi, i'm having this error, do you know what could be? I'm trying to run it on Linux under WINE, and if you know what could happen this on windows maybe i can fix it for Linux.
I didn't found any other ps3 game debugger kinda to test
```
Unhandled Exception: System.PlatformNotSupportedException: Speech Recognition is not available on this system. SAPI and Speech Recognition engines cannot be found.
   at System.Speech.Internal.SapiInterop.SapiRecognizer..ctor(RecognizerType type)
   at System.Speech.Recognition.SpeechRecognitionEngine.Initialize(RecognizerInfo recognizerInfo)
   at System.Speech.Recognition.SpeechRecognitionEngine..ctor()
   at NetCheatPS3.Form1..ctor()
   at NetCheatPS3.Program.Main()
```

**Comment by Dnawrkshp** [comment]
It looks like WINE doesn't support the speech recognition framework.

From googling I found this: https://forum.winehq.org/viewtopic.php?t=28677 which says to try the command:
```
winetricks -q speechsdk
```

**Comment by Klairm** [comment]
Okay, that fixed that issue, but now i'm having a little problem, when i try to connect it says failed to connect to ps3, i select the CCAPI mode , and i have installed ccapi on the same wine prefix, anyway i will try to fix that, thnks you very much
